name: Setup Python env
description: Install Python requirements and testing tools

inputs:
  python-version:
    description: 'Python version'
    required: true
    default: '3.8'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - name: Update pip
      run: python -m pip install --upgrade pip
      shell: bash
    - name: Install dependencies and tools
      run: |
        pip install flake8 pytest
        pip install -r requirements.txt
      shell: bash
