# 2022-01-22 00:16:36.055324
from alembic import op
import sqlalchemy as sa

revision = 'e4352b179e59'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_ongoing', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_session'))
    )
    op.create_table('telegram_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_group')),
    sa.UniqueConstraint('tg_id', name=op.f('uq_telegram_group_tg_id'))
    )
    op.create_table('telegram_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_user')),
    sa.UniqueConstraint('tg_id', name=op.f('uq_telegram_user_tg_id'))
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mu', sa.Float(), nullable=False),
    sa.Column('sigma', sa.Float(), nullable=False),
    sa.Column('game_session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_session.id'], name=op.f('fk_player_game_session_id_game_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player')),
    sa.UniqueConstraint('name', name=op.f('uq_player_name'))
    )
    op.create_table('telegram_user_in_group',
    sa.Column('telegram_user_id', sa.Integer(), nullable=False),
    sa.Column('telegram_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['telegram_group_id'], ['telegram_group.id'], name=op.f('fk_telegram_user_in_group_telegram_group_id_telegram_group')),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['telegram_user.id'], name=op.f('fk_telegram_user_in_group_telegram_user_id_telegram_user')),
    sa.PrimaryKeyConstraint('telegram_user_id', 'telegram_group_id', name=op.f('pk_telegram_user_in_group'))
    )
    op.create_table('telegram_user_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('telegram_user_id', sa.Integer(), nullable=False),
    sa.Column('telegram_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['telegram_group_id'], ['telegram_group.id'], name=op.f('fk_telegram_user_request_telegram_group_id_telegram_group')),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['telegram_user.id'], name=op.f('fk_telegram_user_request_telegram_user_id_telegram_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_user_request'))
    )
    op.create_table('participation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('game_session_id', sa.Integer(), nullable=True),
    sa.Column('match_number', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_session.id'], name=op.f('fk_participation_game_session_id_game_session')),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('fk_participation_player_id_player')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participation'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participation')
    op.drop_table('telegram_user_request')
    op.drop_table('telegram_user_in_group')
    op.drop_table('player')
    op.drop_table('telegram_user')
    op.drop_table('telegram_group')
    op.drop_table('game_session')
    # ### end Alembic commands ###
