# 2022-01-22 13:53:46.084430
from alembic import op
import sqlalchemy as sa

revision = '7a1702e73d8f'
down_revision = 'f01fa40ba29b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_ranking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_group_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_ranking')),
    sa.UniqueConstraint('tg_group_id', name=op.f('uq_game_ranking_tg_group_id'))
    )
    op.create_table('game_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_ongoing', sa.Boolean(), nullable=False),
    sa.Column('game_ranking_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_ranking_id'], ['game_ranking.id'], name=op.f('fk_game_session_game_ranking_id_game_ranking')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_session'))
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mu', sa.Float(), nullable=False),
    sa.Column('sigma', sa.Float(), nullable=False),
    sa.Column('game_ranking_id', sa.Integer(), nullable=False),
    sa.Column('game_session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_ranking_id'], ['game_ranking.id'], name=op.f('fk_player_game_ranking_id_game_ranking')),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_session.id'], name=op.f('fk_player_game_session_id_game_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player')),
    sa.UniqueConstraint('name', name=op.f('uq_player_name'))
    )
    op.create_table('participation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('game_session_id', sa.Integer(), nullable=True),
    sa.Column('match_number', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_session.id'], name=op.f('fk_participation_game_session_id_game_session')),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('fk_participation_player_id_player')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participation'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participation')
    op.drop_table('player')
    op.drop_table('game_session')
    op.drop_table('game_ranking')
    # ### end Alembic commands ###
