# 2022-01-27 23:29:18.841221
from alembic import op
import sqlalchemy as sa

revision = '6fb7106388ef'
down_revision = '2ec55711d647'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
