# 2022-01-23 00:39:58.668566
from alembic import op
import sqlalchemy as sa

revision = '2ec55711d647'
down_revision = '6ee0702a3d64'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
