# 2022-01-17 23:26:17.898478
from alembic import op
import sqlalchemy as sa

revision = '3b79d4331e0f'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_group')),
    sa.UniqueConstraint('tg_id', name=op.f('uq_telegram_group_tg_id'))
    )
    op.create_table('telegram_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_user')),
    sa.UniqueConstraint('tg_id', name=op.f('uq_telegram_user_tg_id'))
    )
    op.create_table('telegram_user_in_group',
    sa.Column('telegram_user_id', sa.Integer(), nullable=False),
    sa.Column('telegram_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['telegram_group_id'], ['telegram_group.id'], name=op.f('fk_telegram_user_in_group_telegram_group_id_telegram_group')),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['telegram_user.id'], name=op.f('fk_telegram_user_in_group_telegram_user_id_telegram_user')),
    sa.PrimaryKeyConstraint('telegram_user_id', 'telegram_group_id', name=op.f('pk_telegram_user_in_group'))
    )
    op.create_table('telegram_user_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('telegram_user_id', sa.Integer(), nullable=False),
    sa.Column('telegram_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['telegram_group_id'], ['telegram_group.id'], name=op.f('fk_telegram_user_request_telegram_group_id_telegram_group')),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['telegram_user.id'], name=op.f('fk_telegram_user_request_telegram_user_id_telegram_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_user_request'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_user_request')
    op.drop_table('telegram_user_in_group')
    op.drop_table('telegram_user')
    op.drop_table('telegram_group')
    # ### end Alembic commands ###
