# 2022-01-19 22:05:32.971900
from alembic import op
import sqlalchemy as sa

revision = 'f0eae71f01c2'
down_revision = '3b79d4331e0f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_ongoing', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_session'))
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mu', sa.Float(), nullable=False),
    sa.Column('sigma', sa.Float(), nullable=False),
    sa.Column('game_session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_session.id'], name=op.f('fk_player_game_session_id_game_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player')),
    sa.UniqueConstraint('name', name=op.f('uq_player_name'))
    )
    op.create_table('participation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('game_session_id', sa.Integer(), nullable=True),
    sa.Column('match_number', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_session.id'], name=op.f('fk_participation_game_session_id_game_session')),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('fk_participation_player_id_player')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participation'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participation')
    op.drop_table('player')
    op.drop_table('game_session')
    # ### end Alembic commands ###
