name: Python unit-tests

on:
  push:
  schedule:
    - cron: '0 9 * * 1,4'

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    strategy:
      matrix:
        python-version: [ 3.8 ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: Lint
        run: flake8 . --config=.github/.flake8 --exit-zero

  test:
    runs-on: ubuntu-latest
    name: Test
    strategy:
      matrix:
        python-version: [ 3.8, 3.9 ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test
        run: |
          coverage run scripts/run_tests.py
          coverage xml -i
      - name: Upload coverage
        uses: codecov/codecov-action@v2
